type Query {
  pins(uid: Int): [pins]!
  GHclientId: String!
}

type Mutation {
  createUserWithEmail(name: String, email: String!, pw: String!): LoggedInUser
  loginWith(provider: provider!, email: String!, code: String!): LoggedInUser
  logout(token: String!): Int
  createPin(url: String!, token: String!, title: String, description: String): Int
  delPin(id: Int!, token: String!): Int

}

type LoggedInUser {
  id: Int!
  ts: Int
  name: String
  email: String
  gh: String
  gh_name: String
  token: String
}

type pins {
  id: Int!
  ts: Int
  uid: Int!
  url: String!
  title: String
  description: String
}

enum provider {
  email 
  gh # github
  token
}